### ISSUE TITLE
Unable to install on Debian10

### ISSUE THREAD

**Issue by ahrensdc** [jepio/azure-keyvault-pgp#1]
When I run the command go get -u -v github,com/jepio/azure-keyvault-pgp, I get:

github.com/jepio/azure-keyvault-pgp imports
   ...
   github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys/crypto:  cannot find module providing package github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys/crypto 

Regards,
Dave

**Comment by jepio** [comment]
Sorry, missed this.

azure-sdk-for-go was restructured upstream, i've now adapted this repo to it, that should fix this issue. It won't work with the system Go compiler in Debian 10 though, because the dependencies require Go 1.18 min. I don't know a way around that.
